{
  "GATEWAY_INTERFACE"              => "CGI/1.1",
  "HTTP_VERSION"                   => "HTTP/1.1",
  "REQUEST_PATH"                   => "/",
  "PATH_INFO"                      => "/",
  "QUERY_STRING"                   => "",
  "REMOTE_ADDR"                    => "::1",
  "REMOTE_HOST"                    => "localhost",
  "REQUEST_METHOD"                 => "GET",
  "REQUEST_URI"                    => "http://localhost:9292/",
  "SCRIPT_NAME"                    => "",
  "SERVER_NAME"                    => "localhost",
  "SERVER_PORT"                    => "9292",
  "SERVER_PROTOCOL"                => "HTTP/1.1",
  "SERVER_SOFTWARE"                => "WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)",
  "HTTP_HOST"                      => "localhost:9292",
  "HTTP_CONNECTION"                => "keep-alive",
  "HTTP_CACHE_CONTROL"             => "max-age=0",
  "HTTP_ACCEPT"                    => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "HTTP_UPGRADE_INSECURE_REQUESTS" => "1",
  "HTTP_USER_AGENT"                => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36",
  "HTTP_ACCEPT_ENCODING"           => "gzip, deflate, sdch",
  "HTTP_ACCEPT_LANGUAGE"           => "en-US,en;q=0.8",
  "rack.version"                   => [1, 3],
  "rack.input"                     => #<Rack::Lint::InputWrapper:0x007fb2098c7f18 @input=#<StringIO:0x007fb2098d69c8>>,
  "rack.errors"                    => #<Rack::Lint::ErrorWrapper:0x007fb2098c7ec8 @error=#<IO:<STDERR>>>,
  "rack.multithread"               => true,
  "rack.multiprocess"              => false,
  "rack.run_once"                  => false,
  "rack.url_scheme"                => "http",
  "rack.hijack?"                   => true,
  "rack.hijack_io"                 => nil,
  "rack.tempfiles"                 => []
}
